DROP TABLE IF EXISTS resources CASCADE;

CREATE TABLE resources(
  id SERIAL PRIMARY KEY NOT NULL,
  topic_id INTEGER REFERENCES topics(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  link VARCHAR(255) NOT NULL
);