DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE comments(
  id SERIAL PRIMARY KEY NOT NULL,
  resource_id INTEGER REFERENCES resources(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  parent_id INTEGER DEFAULT NULL,
  posted_date DATE NOT NULL DEFAULT CURRENT_DATE,
  comment VARCHAR(255) NOT NULL
);